# Generated by Django 4.1.7 on 2023-03-21 01:35

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='بیوگرافی')),
                ('phone', models.CharField(blank=True, help_text='همراه با صفر وارد شود', max_length=11, null=True, verbose_name='شماره تلفن')),
                ('gender', models.CharField(choices=[('m', 'آقا'), ('f', 'خانم'), ('o', 'سایر')], max_length=1, verbose_name='جنسیت')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='acounts/avatars/', verbose_name='آواتار')),
                ('nc', models.CharField(max_length=11, verbose_name='کد ملی')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'پروفایل',
                'verbose_name_plural': 'پروفایل ها',
            },
        ),
    ]
