# Generated by Django 4.1.7 on 2023-03-18 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='default value', max_length=50, verbose_name='دسته بندی'),
        ),
    ]
